name: Convert Markdown to HTML for GitHub Pages

permissions:
  contents: write
  pages: write 

on:
  push:
    branches:
      - main  # Or whichever branch you want to trigger from

jobs:
  convert-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      
      - name: Find and convert markdown files
        run: |
          # Find all markdown files and convert them to HTML
          find . -name "*.md" -type f -print0 | while IFS= read -r -d '' file; do
            # Get the filename without extension
            filename=$(basename -- "$file")
            dirname=$(dirname -- "$file")
            filename_noext="${filename%.*}"
            
            # Convert to HTML and maintain directory structure
            echo "Converting $file to $dirname/$filename_noext.html"
            pandoc -s "$file" -o "$dirname/$filename_noext.html"  --to=html5 --katex --citeproc -d ./template/defaults.yml
          done
      
      - name: Remove markdown files
        run: |
          # Remove all markdown files except README.md
          find . -name "*.md" -type f -not -name "README.md" -delete
      - name: Remove bib files
        run: |
          find . -name "*.bib" -type f -delete
      - name: Remove template files
        run: |
          rm -rf ./template
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # The folder containing the built site
          branch: gh-pages  # The branch to deploy to
          clean: true  # Automatically remove deleted files from the deploy branch
